import { max } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";

import { auditLogs } from "../src/lib/server/db/schema";

// Records the audit_logs high-water mark before any test runs. expense.spec.ts
// deletes the transaction it creates, but the recordAudit entries persist by
// design; global-teardown uses this baseline to remove only the audit rows
// generated by this run, leaving pre-existing audit history untouched.
export default async function globalSetup() {
  process.loadEnvFile(".env");
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error("DATABASE_URL is not set");
  }

  const client = postgres(databaseUrl, { max: 1 });
  const db = drizzle(client);
  try {
    const [row] = await db.select({ maxId: max(auditLogs.id) }).from(auditLogs);
    process.env.E2E_AUDIT_BASELINE_ID = String(row?.maxId ?? 0);
  } finally {
    await client.end();
  }
}
